name: serverTest #NOMBRE

on: [workflow_dispatch] #ACCION QUE ACTIVA EL ACTION

jobs:
  job1:
    runs-on: ubuntu-latest #MAQUINA EN LA QUE CORRE

    strategy:
      matrix:
        node-version: [14.x]
    steps:  #PASOS A SEGUIR
      - uses: actions/checkout@v2 #CLONAR EL PROYECTO EN LA MAQUINA VIRTUAL
      - name: Use Node.js ${{ matrix.node-version }} # NOMBRE DE LA PRUEBA
        uses: actions/setup-node@v1 
      - run: | #COMANDOS
          npm install 
          npm test
