name: serverTest #NOMBRE

on: [workflow_dispatch] #ACCION QUE ACTIVA EL ACTION

jobs:
  job1:
    runs-on: ubuntu-latest #MAQUINA EN LA QUE CORRE

    strategy:
      matrix:
        node-version: [14.x]
    steps:  #PASOS A SEGUIR
      - uses: actions/checkout@v2 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - run: |
          npm install 
          npm test
